### ISSUE TITLE
Ubuntu 18.04 LTS apt update error

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/archivesspace-development#12]
I have been consistently reproducing the following:

```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/universe/binary-amd64/by-hash/SHA256/ca221e8754c933c636b6c0a344617e3444a7c8cb0982ca97725cda9b7bfe1e6a  Hash Sum mismatch
```
(I believe that this is related to https://askubuntu.com/questions/1215577/failed-to-fetch-url-hash-sum-mismatch-ubuntu-18-04-lts)

This blocks progress on this by preventing one from building the Docker environment.

**Comment by jrgriffiniii** [comment]
While I have resolved this, there is now an additional error from the Maven steps in the build:

```
BUILD FAILED
/source/build/build.xml:813: The following error occurred while executing this line:
/source/build/build.xml:78: javax.net.ssl.SSLException: Tag mismatch!
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
       at sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1037)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:948)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.MeteredStream.read(MeteredStream.java:134)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3454)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3447)
        at org.apache.tools.ant.taskdefs.Get$GetThread.downloadFile(Get.java:830)
        at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:656)
        at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:640)
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
        at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:592)
```

**Comment by jrgriffiniii** [comment]
This seems to be fine on CircleCI (please see https://app.circleci.com/pipelines/github/pulibrary/archivesspace-development/20/workflows/68260c4d-701f-4272-8982-3a875195706b/jobs/35), hence I suspect that this now may be due to a Docker Desktop on Mac or local network caching issue.

**Comment by jrgriffiniii** [comment]
Rebooting my local development environment after a GlobalProtect upgrade seems to have resolved this.
